### ISSUE TITLE
Weird highlight

### ISSUE THREAD

**Issue by ghost** [yosssi/vim-gold#1]
I took a code sample from [yosssi/gold](https://github.com/yosssi/gold)/[README.md](https://github.com/yosssi/gold/blob/9c695cfb7a279d14151246b2788d3edeeff582a3/README.md) and opened it up in vim, and this is the highlight I get.

![screenshot from 2014-07-15 17 28 06](https://cloud.githubusercontent.com/assets/6207198/3592012/af3bcdbc-0c6b-11e4-85bf-a40ba82e340f.png)

Why do `content` get hightlighted? (lines 7 and 14) And it would be nice if `footer`, `block` and `extends` keywords got some color (:

Thanks.

**Comment by yosssi** [comment]
Thanks for using Gold! I'll fix it later.

**Comment by yosssi** [comment]
@noisypixy 

Hi, I re-created Gold as a new package because I wanted to refine and simplify the source code, data structure and APIs of this package for its future enhancement.

[Ace - HTML template engine for Go](https://github.com/yosssi/ace)

Please use this new package hereafter.

Thanks!
